application:
    security:
        allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:8080
spring:
    application:
        name: exam
    datasource:
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
